name: baisa_beauty
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:  
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
